org: alexddev
service: url-short-cut

plugins:
  - serverless-offline

useDotenv: true

provider:
  name: aws
  runtime: nodejs22.x
  memorySize: 512
  timeout: 30
  architecture: x86_64
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    SHORT_URL_BASE: ${env:SHORT_URL_BASE}
    PRISMA_CLI_BINARY_TARGETS: ${env:PRISMA_CLI_BINARY_TARGETS}
    IPINFO_API_KEY: ${env:IPINFO_API_KEY}

functions:
  createShortCutURL:
    handler: src/functions/shorten.handler
    events:
      - httpApi:
          method: post
          path: /shorten
  createUser:
    handler: src/functions/createUser.handler
    events:
      - httpApi:
          method: post
          path: /users
  redirect:
    handler: src/functions/redirect.handler
    events:
      - httpApi:
          method: get
          path: /{shortUrlId}

package:
  individually: true
  patterns:
    - "!node_modules/.prisma/client/libquery_engine-*"
    - "node_modules/.prisma/client/libquery_engine-rhel-*"
    - "!node_modules/prisma/libquery_engine-*"
    - "!node_modules/@prisma/engines/**"
    - "node_modules/.prisma/client/schema.prisma"
    - "generated/**"
